#!/bin/bash 

WORKTREE_ROOT_DIR=$(realpath $(git rev-parse --git-common-dir))

if [[ -z "$WORKTREE_ROOT_DIR" ]]; then 
  echo 'WORKTREE_ROOT_DIR is not set'
  exit 1
fi

skipPost=""
remoteBranch=""
commitish=""
name=""


while getopts ':s:r::d:b:' opt;
do
  case $opt in 
    s|skip-post) skipPost="true" ;;
    r|remote) remoteBranch="$OPTARG" ;;
    d) commitish="develop" ;;
    b) name="$OPTARG" ;;
    \?) 
      echo "Invalid option: -$OPTARG"
      exit 2
      ;;
    :)
      echo "Option -$OPTARG requires an argument."
      exit 2
      ;;
  esac
done

shift $((OPTIND - 1))


if [[ -z "$name" ]]; then
  echo "Please provide a name for the directory in which to create the new worktree"
  echo "Usage: $0 -b <branch-name> [-r <remote-branch>] [-s] [-d]"
  exit 2
fi

if [[ -z "$remoteBranch" ]]; then
  echo "Setting up new branch $name"
  git worktree add -b "${name}" "${WORKTREE_ROOT_DIR}/branches/${name}"
else
  echo "Setting up remote branch"
  git worktree add "${WORKTREE_ROOT_DIR}/branches/${name}" "$remoteBranch"
fi

cd "${WORKTREE_ROOT_DIR}/branches/${name}"

if [[ -z $skipPost && -x "${WORKTREE_ROOT_DIR}/.post-worktree-add" ]];
then
  bash "${WORKTREE_ROOT_DIR}/.post-worktree-add"
fi

