#! /bin/sh

pgrep -x /usr/bin/dunst >> /dev/null || /usr/bin/dunst &
pgrep -x picom || picom -b

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# if type "xrandr"; then
#   for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
#     MONITOR=$m polybar --reload example &
#   done
# else
#   polybar --reload example &
# fi


pgrep -x sxhkd > /dev/null || sxhkd &

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config border_width 2
